name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: windows
          - os: ubuntu-latest
            artifact-name: linux
          - os: macos-latest
            artifact-name: macos
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2.1.0
        with:
          haxe-version: 4.3.7

      - name: Install hxcpp
        run: |
            haxelib install hxcpp --quiet

      - name: Inspect problematic header
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
            haxelib install hxcpp --quiet
            HXCPP_PATH=$(haxelib path hxcpp | grep -v '^-D' | head -n 1)
            grep -n "^namespace" "$HXCPP_PATH/include/hx/LessThanEq.h"

      - name: Check include chain
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
            HXCPP_PATH=$(haxelib path hxcpp | grep -v '^-D' | head -n 1)
            grep -rn "LessThanEq.h" "$HXCPP_PATH/include"

      # Windowsのみ、MSVCのcl.exeをPATHに通す
      - name: Setup MSVC (Windows only)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Compile build tool itself
        run: haxe build.hxml

      - name: Run HConstruct build
        run: |
          ${{ matrix.os == 'windows-latest' && '.\bin\Build.exe' || './bin/Build' }} samples/.HConstruct
        continue-on-error: true
    
      - name: Inspect Std.cpp includes
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
            head -n '60,90p' out/cpp/src/Std.cpp
    
      - name: Inspect hxcpp.h around LessThanEq include
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
            HXCPP_PATH=$(haxelib path hxcpp | grep -v '^-D' | head -n 1)
            sed -n '360,390p' "$HXCPP_PATH/include/hxcpp.h"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ matrix.artifact-name }}
          path: |
            out/MyApp
            out/MyApp.exe
          if-no-files-found: ignore