name: "[Build] run.hxml -> run.n"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2.1.0
        with:
          haxe-version: 4.3.7

      - name: Compile of run.hxml
        run: haxe run.hxml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: runfile
          path: run.n
          if-no-files-found: ignore