name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: windows
          - os: ubuntu-latest
            artifact-name: linux
          - os: macos-latest
            artifact-name: macos
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2.1.0
        with:
          haxe-version: 4.3.7

      - name: Install hxcpp
        run: |
            haxelib install hxcpp --quiet

      - name: Check hxcpp bin directory
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
            HXCPP_PATH=$(haxelib path hxcpp | grep -v '^-D' | head -n 1)
            find "$HXCPP_PATH/bin" -type f

      # Windowsのみ、MSVCのcl.exeをPATHに通す
      - name: Setup MSVC (Windows only)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1.13.0
    
      - name: Build hxcpp runtime (release version)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
            HXCPP_PATH=$(haxelib path hxcpp | grep -v '^-D' | head -n 1)
            cd "$HXCPP_PATH/project"
            haxelib run hxcpp Build.xml -Dmac -DHXCPP_M64

      - name: Compile build tool itself
        run: haxe build.hxml

      - name: Run HConstruct build
        run: |
          ${{ matrix.os == 'windows-latest' && '.\bin\Build.exe' || './bin/Build' }} samples/.HConstruct
        continue-on-error: true
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ matrix.artifact-name }}
          path: |
            out/MyApp
            out/MyApp.exe
          if-no-files-found: ignore